package entertheblack.gui.components;

import java.awt.Graphics2D;

import entertheblack.gui.ActionListener;
import entertheblack.menu.Assets;

// Button specifically designed to be used by Options/Controls.

public class KeyButton extends Button {
	int key; // What key from Assets.Controls this button is supposed to change.

	public KeyButton(int x, int y, int width, int height, ActionListener l, int id, String t, int key) {
		super(x, y, width, height, l, id, t);
		this.key = key;
	}
	
	@Override
	public void paint(Graphics2D g) {
		super.paint(g);
		if(Assets.Controls[key] < codeToText.length)
			g.drawString(codeToText[Assets.Controls[key]], x + 10, y + 50);
		else
			g.drawString("?", x + 10, y + 50);
	}
	
	// What keys are represented by a keyCode:
	private String[] codeToText = {
			"?", 						//0x00;
			"?", 						//0x01;
			"?", 						//0x02;
		    "Cancel",					//0x03;
			"?", 						//0x04;
			"?", 						//0x05;
			"?", 						//0x06;
			"?", 						//0x07;
		    "Backspace",				//0x08;
		    "Tab",						//0x09;
			"Enter",					//0x0A;
			"?", 						//0x0B;
		    "Clear",					//0x0C;
			"?", 						//0x0D;
			"?", 						//0x0E;
			"?", 						//0x0F;
		    "Shift",					//0x10;
		    "Control",					//0x11;
		    "Alt",						//0x12;
		    "Pause",					//0x13;
		    "Caps Lock",				//0x14;
		    "Kana",						//0x15;
			"?", 						//0x16;
			"?", 						//0x17;
		    "Final",					//0x18;
		    "Knaji",					//0x19;
		    "?",						//0x1A;
		    "Escape",					//0x1B;
		    "Convert",					//0x1C;
		    "Non Convert",				//0x1D;
		    "Acccept",					//0x1E;
		    "Mode Change",				//0x1F;
		    "Space",					//0x20;
		    "Page Up",					//0x21;
		    "Page Down",				//0x22;
		    "End",						//0x23;
		    "Home",						//0x24;
		    "Left",						//0x25;
		    "Up",						//0x26;
		    "Right",					//0x27;
		    "Down",						//0x28;
			"?", 						//0x29;
			"?", 						//0x2A;
			"?", 						//0x2B;
		    "Comma",					//0x2C;
		    "Minus",					//0x2D;
		    "Period",					//0x2E;
		    "Slash",					//0x2F;
		    "0",						//0x30;
		    "1",						//0x31;
		    "2",						//0x32;
		    "3",						//0x33;
		    "4",						//0x34;
		    "5",						//0x35;
		    "6",						//0x36;
		    "7",						//0x37;
		    "8",						//0x38;
		    "9",						//0x39;
			"?", 						//0x3A;
		    "Semicolon",				//0x3B;
			"?", 						//0x3C;
		    "Equals",					//0x3D;
			"?", 						//0x3E;
			"?", 						//0x3F;
			"?", 						//0x40;
			"A",						//0x41;
			"B",						//0x42;
			"C",						//0x43;
			"D",						//0x44;
			"E",						//0x45;
			"F",						//0x46;
			"G",						//0x47;
			"H",						//0x48;
			"I",						//0x49;
			"J",						//0x4A;
			"K",						//0x4B;
			"L",						//0x4C;
			"M",						//0x4D;
			"N",						//0x4E;
			"O",						//0x4F;
			"P",						//0x50;
			"Q",						//0x51;
			"R",						//0x52;
			"S",						//0x53;
			"T",						//0x54;
			"U",						//0x55;
			"V",						//0x56;
			"W",						//0x57;
			"X",						//0x58;
			"Y",						//0x59;
			"Z",						//0x5A;
		    "Open Bracket",				//0x5B;
		    "Backslash",				//0x5C;
		    "Close Bracket",			//0x5D;
			"?", 						//0x5E;
			"?", 						//0x5F;
		    "Numpad 0",					//0x60;
		    "Numpad 1",					//0x61;
		    "Numpad 2",					//0x62;
		    "Numpad 3",					//0x63;
		    "Numpad 4",					//0x64;
		    "Numpad 5",					//0x65;
		    "Numpad 6",					//0x66;
		    "Numpad 7",					//0x67;
		    "Numpad 8",					//0x68;
		    "Numpad 9",					//0x69;
		    "Multiply",					//0x6A;
		    "Add",						//0x6B;
		    "Separator",				//0x6C;
		    "Subtract",					//0x6D;
		    "Decimal",					//0x6E;
		    "Divide",					//0x6F;
		    "F1",						//0x70;
		    "F2",						//0x71;
		    "F3",						//0x72;
		    "F4",						//0x73;
		    "F5",						//0x74;
		    "F6",						//0x75;
		    "F7",						//0x76;
		    "F8",						//0x77;
		    "F9",						//0x78;
		    "F10",						//0x79;
		    "F11",						//0x7A;
		    "F12",						//0x7B;
			"?", 						//0x7C;
			"?", 						//0x7D;
			"?", 						//0x7E;
		    "Delete",					//0x7F;
		    "Dead Grave",				//0x80;
		    "Dead Acute", 				//0x81;
		    "Dead Circumflex",			//0x82;
		    "Dead Tilde",				//0x83;
		    "Dead Macron",				//0x84;
		    "Dead Breve",				//0x85;
		    "Dead Abovedot",			//0x86;
		    "Dead Diaeresis",			//0x87;
		    "Dead Abovering",			//0x88;
		    "Dead Doubleacute",			//0x89;
		    "Dead Caron",				//0x8a;
		    "Dead Cedilla",				//0x8b;
		    "Dead Ogonek",				//0x8c;
		    "Dead Iota",				//0x8d;
		    "Dead Voiced Sound",		//0x8e;
		    "Dead Semivoice Sound",		//0x8f;
		    "Numlock",					//0x90;
		    "Scroll lock",				//0x91;
			"?", 						//0x92;
			"?", 						//0x93;
			"?", 						//0x94;
			"?", 						//0x95;
		    "Ampersand",				//0x96;
		    "Asterik",					//0x97;
		    "Quotedbl",					//0x98;
		    "Less",						//0x99;
		    "Print",					//0x9A;
		    "Insert",					//0x9B;
		    "Help",						//0x9C;
		    "Meta",						//0x9D;
			"?", 						//0x9E;
			"?", 						//0x9F;
		    "Greater",					//0xA0;
		    "Brace Left",				//0xA1;
		    "Brace Right",				//0xA2;
			"?", 						//0xA3;
			"?", 						//0xA4;
			"?", 						//0xA5;
			"?", 						//0xA6;
			"?", 						//0xA7;
			"?", 						//0xA8;
			"?", 						//0xA9;
			"?", 						//0xAA;
			"?", 						//0xAB;
			"?", 						//0xAC;
			"?", 						//0xAD;
			"?", 						//0xAE;
			"?", 						//0xAF;
			"?", 						//0xB0;
			"?", 						//0xB1;
			"?", 						//0xB2;
			"?", 						//0xB3;
			"?", 						//0xB4;
			"?", 						//0xB5;
			"?", 						//0xB6;
			"?", 						//0xB7;
			"?", 						//0xB8;
			"?", 						//0xB9;
			"?", 						//0xBA;
			"?", 						//0xBB;
			"?", 						//0xBC;
			"?", 						//0xBD;
			"?", 						//0xBE;
			"?", 						//0xBF;
		    "Back Quote",				//0xC0;
			"?", 						//0xC1;
			"?", 						//0xC2;
			"?", 						//0xC3;
			"?", 						//0xC4;
			"?", 						//0xC5;
			"?", 						//0xC6;
			"?", 						//0xC7;
			"?", 						//0xC8;
			"?", 						//0xC9;
			"?", 						//0xCA;
			"?", 						//0xCB;
			"?", 						//0xCC;
			"?", 						//0xCD;
			"?", 						//0xCE;
			"?", 						//0xCF;
			"?", 						//0xD0;
			"?", 						//0xD1;
			"?", 						//0xD2;
			"?", 						//0xD3;
			"?", 						//0xD4;
			"?", 						//0xD5;
			"?", 						//0xD6;
			"?", 						//0xD7;
			"?", 						//0xD8;
			"?", 						//0xD9;
			"?", 						//0xDA;
			"?", 						//0xDB;
			"?", 						//0xDC;
			"?", 						//0xDD;
		    "Quote",					//0xDE;
			"?", 						//0xDF;
		    "KP Up",					//0xE0;
		    "KP Down",					//0xE1;
		    "KP Left",					//0xE2;
		    "KP Right",					//0xE3;
			"?", 						//0xE4;
			"?", 						//0xE5;
			"?", 						//0xE6;
			"?", 						//0xE7;
			"?", 						//0xE8;
			"?", 						//0xE9;
			"?", 						//0xEA;
			"?", 						//0xEB;
			"?", 						//0xEC;
			"?", 						//0xED;
			"?", 						//0xEE;
			"?", 						//0xEF;
		    "Alphanumeric",				//0xF0;
		    "Katakana",					//0xF1;
		    "Hiragana",					//0xF2;
		    "Full Width",				//0xF3;
		    "Half Width",				//0xF4;
		    "Roman Character",			//0xF5;
			"?", 						//0xF6;
			"?", 						//0xF7;
			"?", 						//0xF8;
			"?", 						//0xF9;
			"?", 						//0xFA;
			"?", 						//0xFB;
			"?", 						//0xFC;
			"?", 						//0xFD;
			"?", 						//0xFE;
			"?", 						//0xFF;
		    "All Candidates",			//0x100;
		    "Previous Candidates",		//0x101;
		    "Code Input",				//0x102;
		    "Japanese Katakana",		//0x103;
		    "Japanese Hiragana",		//0x104;
		    "Japanese Roman",			//0x105;
		    "Kana Lock",				//0x106;
		    "Input Method On/Off",		//0x107;
	};
}
